DATASET:
  TRAIN: "/home/tunguyen/Early-Fire-Prediction/datasets/fire/train/"
  VAL: "/home/tunguyen/Early-Fire-Prediction/datasets/fire/valid/"
  TEST: "/home/tunguyen/Early-Fire-Prediction/datasets/fire/test/"
  CLASS_NAMES:
    - "NoFire"
    - "Fire"
    - "Smoke"
MODEL:
  N_FRAMES: 8
  FRAME_STEP: 20
  INPUT_WIDTH: 112
  INPUT_HEIGHT: 112
TRAIN:
  LR: 0.0001
  BATCH_SIZE: 8
  NUM_EPOCHS: 20 